#!/usr/bin/env bash
# Turn this checkout into the iOS variant: the app without the Swiss Ephemeris.
#
# ⚠ **Why this exists.** AGPL software cannot be distributed through Apple's
# App Store — its terms impose restrictions the licence forbids adding — and the
# Swiss Ephemeris belongs to its own authors rather than to her, so no
# permission of hers can cover it. The iOS build therefore computes the sky from
# published theory instead: VSOP87 and the abridged lunar theory, neither of
# which carries a software licence at all.
#
# ⚠ **A runtime switch would not do.** A package listed in pubspec.yaml has its
# native side compiled into the binary whether or not a line of Dart calls it.
# The dependency has to be ABSENT, which is why this edits the manifest and not
# a flag.
#
# ⚠ **Temporary, and meant to be deleted.** When the commercial licence is
# bought, iOS goes back to the same engine as Android: delete lib/sky/public.dart
# and its data, delete this script, and the app is one engine again. Nothing
# above lib/sky/sky.dart knows which answered, which is what keeps that small.
#
# It edits the working tree in place and is meant to run in CI on a throwaway
# checkout. Running it on a laptop leaves the tree changed; `git checkout .`
# puts it back.
set -euo pipefail
cd "$(dirname "$0")/.."

say() { printf '  %s\n' "$*"; }

# ── 1. the engine ───────────────────────────────────────────────────────────
cat > lib/sky/current.dart <<'DART'
// SPDX-License-Identifier: AGPL-3.0-only
//
// Which engine answers — the iOS variant.
//
// ⚠ GENERATED by tool/make_ios_variant.sh. The Android build's version of this
// file names the Swiss implementation; this one cannot, because that library
// is not in this build at all.
import 'public.dart';
import 'sky.dart';

/// The sky, as this build computes it.
const Sky sky = PublicSky();
DART
say "lib/sky/current.dart now names the public-domain engine"

# ── 2. the implementation that needs the library ────────────────────────────
rm -f lib/sky/swiss.dart
say "lib/sky/swiss.dart removed"

# ── 3. the dependency itself ────────────────────────────────────────────────
#
# ⚠ Both the package and its assets. Leaving the asset lines behind makes the
# build fail with "unable to find directory entry in pubspec.yaml", which names
# the assets and not the missing package.
python3 - <<'PY'
import re
p = 'pubspec.yaml'
s = open(p).read()
before = s
s = re.sub(r'(?m)^\s+sweph:.*\n', '', s)
s = re.sub(r'(?m)^\s+- packages/sweph/.*\n', '', s)
assert s != before, 'nothing removed — has the manifest changed shape?'
open(p, 'w').write(s)
PY
say "sweph removed from pubspec.yaml"

# ── 4. the tests that can only run against it ───────────────────────────────
#
# ⚠ Removed rather than left to fail. The device test that holds the Swiss
# implementation to the website cannot run in a build that does not contain it;
# the HOST test that holds the PUBLIC engine to the same fixture stays, and is
# the one that matters here.
rm -f integration_test/agrees_with_the_website_test.dart
say "the Swiss-only agreement test removed (the public-domain one remains)"

echo
say "This checkout is now the iOS variant."
say "Check it with:  flutter analyze && flutter test"
